# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on

before:
  hooks:
    - go mod verify
builds:
  -
    id: "und"
    binary: und
    main: ./cmd/und
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=UndMainchain
      - -X github.com/cosmos/cosmos-sdk/version.ServerName=und
      - -X github.com/cosmos/cosmos-sdk/version.ClientName=undcli
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.FullCommit}}
      - -X "github.com/cosmos/cosmos-sdk/version.BuildTags={{.Env.UND_BUILD_TAGS}}"
    flags:
      - -mod=readonly
      - -tags="{{.Env.UND_BUILD_TAGS}}"
    hooks:
      pre: go mod verify
  -
    id: "undcli"
    binary: undcli
    main: ./cmd/undcli
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=UndMainchain
      - -X github.com/cosmos/cosmos-sdk/version.ServerName=und
      - -X github.com/cosmos/cosmos-sdk/version.ClientName=undcli
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.FullCommit}}
      - -X "github.com/cosmos/cosmos-sdk/version.BuildTags={{.Env.UND_BUILD_TAGS}}"
    flags:
      - -mod=readonly
      - -tags="{{.Env.UND_BUILD_TAGS}}"
    hooks:
      pre: go mod verify

archives:
  -
    id: "und"
    builds:
      - und
    name_template: "{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    replacements:
      amd64: x86_64
    files:
      - docs/*
      - LICENSE
      - README.md

  -
    id: "undcli"
    builds:
      - undcli
    name_template: "{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: x86_64
      darwin: osx
    files:
      - docs/*
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
      - '^build:'
      - '^dist:'
