version: "3"
services:
  node1:
    hostname: node1
    build:
      context: ..
      dockerfile: ./Docker/validator.systemtest/Dockerfile
      args:
        WITH_DELVE: "no"
        GO_VERSION: 1.13.1
    container_name: node1
    command: python -m mainnet.systemtest.upgrade
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.3
    ports:
      - "26661:26661"

networks:
  mainchain_devnet:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
