version: "3"
services:
  node1:
    hostname: node1
    build:
      context: ..
      dockerfile: ./Docker/validator.upstream/Dockerfile
    container_name: node1
    command: /root/.go/bin/und start --home /root/.und_mainchain/node1 --rpc.laddr=tcp://0.0.0.0:26661 --log_level="main:info,state:info,x/enterprise:debug,x/beacon:debug,x/wrkchain:debug,*:error"
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.3
    ports:
      - "26661:26661"

  node2:
    hostname: node2
    build:
      context: ..
      dockerfile: ./Docker/validator.upstream/Dockerfile
    container_name: node2
    command: /root/.go/bin/und start --home /root/.und_mainchain/node2 --rpc.laddr=tcp://0.0.0.0:26662 --log_level="main:info,state:info,x/enterprise:debug,x/beacon:debug,x/wrkchain:debug,*:error"
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.4
    ports:
      - "26662:26662"

  node3:
    hostname: node3
    build:
      context: ..
      dockerfile: ./Docker/validator.upstream/Dockerfile
    container_name: node3
    command: /root/.go/bin/und start --home /root/.und_mainchain/node3 --rpc.laddr=tcp://0.0.0.0:26663 --log_level="main:info,state:info,x/enterprise:debug,x/beacon:debug,x/wrkchain:debug,*:error"
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.5
    ports:
      - "26663:26663"

  rest-server:
    hostname: rest-server
    build:
      context: ..
      dockerfile: ./Docker/validator.local/Dockerfile
      args:
        WITH_DELVE: "no"
    container_name: rest-server
    command: >
      /bin/sh -c "
        until nc -z 172.25.0.3 26661; do sleep 1; echo 'wait for node1'; done
        echo 'wait for first block'
        sleep 10
        /root/.go/bin/undcli rest-server --laddr=tcp://0.0.0.0:1317 --node tcp://172.25.0.3:26661 --chain-id=UND-Mainchain-DevNet --trust-node=false
      "
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.6
    ports:
      - "1317:1317"

networks:
  mainchain_devnet:
    ipam:
      driver: default
      config:
      - subnet: 172.25.0.0/24
